# Generated by Django 5.0.3 on 2024-03-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_remove_pagelink_url_pagelink_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagelink",
            name="platform",
            field=models.CharField(
                choices=[
                    ("youtube", "YouTube"),
                    ("tiktok", "TikTok"),
                    ("x", "X"),
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("spotify", "Spotify Artist ID"),
                    ("discord", "Discord Invite ID"),
                    ("telegram", "Telegram"),
                    ("whatsapp", "WhatsApp"),
                    ("tumblr", "Tumblr"),
                    ("reddit", "Reddit"),
                    ("cash_app", "Cash App"),
                    ("paypal", "PayPal"),
                    ("github", "GitHub"),
                    ("other", "Website"),
                ],
                default="other",
                max_length=255,
            ),
        ),
    ]
